[package]
name = "zmk-styler"
version = "0.1.0"
edition = "2021"

[dependencies]
annotate-snippets = "0.11.5"
anstream = "0.6.18"
itertools = "0.14.0"
thiserror = "2.0.11"

[dev-dependencies]
insta = "1.42.0"
